package sirius.web.jdbc;

import sirius.kernel.commons.Watch;

import java.sql.*;

public class WrappedStatement implements Statement {
    private Statement stmt;
    private Databases ds;

    public WrappedStatement(Statement stmt, Databases ds) {
        super();
        this.stmt = stmt;
        this.ds = ds;
    }

    public ResultSet executeQuery(String sql) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.executeQuery(sql);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public <T> T unwrap(Class<T> iface) throws SQLException {
        return stmt.unwrap(iface);
    }

    public int executeUpdate(String sql) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.executeUpdate(sql);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return stmt.isWrapperFor(iface);
    }

    public void close() throws SQLException {
        stmt.close();
    }

    public int getMaxFieldSize() throws SQLException {
        return stmt.getMaxFieldSize();
    }

    public void setMaxFieldSize(int max) throws SQLException {
        stmt.setMaxFieldSize(max);
    }

    public int getMaxRows() throws SQLException {
        return stmt.getMaxRows();
    }

    public void setMaxRows(int max) throws SQLException {
        stmt.setMaxRows(max);
    }

    public void setEscapeProcessing(boolean enable) throws SQLException {
        stmt.setEscapeProcessing(enable);
    }

    public int getQueryTimeout() throws SQLException {
        return stmt.getQueryTimeout();
    }

    public void setQueryTimeout(int seconds) throws SQLException {
        stmt.setQueryTimeout(seconds);
    }

    public void cancel() throws SQLException {
        stmt.cancel();
    }

    public SQLWarning getWarnings() throws SQLException {
        return stmt.getWarnings();
    }

    public void clearWarnings() throws SQLException {
        stmt.clearWarnings();
    }

    public void setCursorName(String name) throws SQLException {
        stmt.setCursorName(name);
    }

    public boolean execute(String sql) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.execute(sql);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public ResultSet getResultSet() throws SQLException {
        return stmt.getResultSet();
    }

    public int getUpdateCount() throws SQLException {
        return stmt.getUpdateCount();
    }

    public boolean getMoreResults() throws SQLException {
        return stmt.getMoreResults();
    }

    public void setFetchDirection(int direction) throws SQLException {
        stmt.setFetchDirection(direction);
    }

    public int getFetchDirection() throws SQLException {
        return stmt.getFetchDirection();
    }

    public void setFetchSize(int rows) throws SQLException {
        stmt.setFetchSize(rows);
    }

    public int getFetchSize() throws SQLException {
        return stmt.getFetchSize();
    }

    public int getResultSetConcurrency() throws SQLException {
        return stmt.getResultSetConcurrency();
    }

    public int getResultSetType() throws SQLException {
        return stmt.getResultSetType();
    }

    public void addBatch(String sql) throws SQLException {
        stmt.addBatch(sql);
    }

    public void clearBatch() throws SQLException {
        stmt.clearBatch();
    }

    public int[] executeBatch() throws SQLException {
        return stmt.executeBatch();
    }

    public Connection getConnection() throws SQLException {
        return stmt.getConnection();
    }

    public boolean getMoreResults(int current) throws SQLException {
        return stmt.getMoreResults(current);
    }

    public ResultSet getGeneratedKeys() throws SQLException {
        return stmt.getGeneratedKeys();
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.executeUpdate(sql, autoGeneratedKeys);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.executeUpdate(sql, columnIndexes);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.executeUpdate(sql, columnNames);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.execute(sql, autoGeneratedKeys);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.execute(sql, columnIndexes);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public boolean execute(String sql, String[] columnNames) throws SQLException {
        Watch w = Watch.start();
        try {
            return stmt.execute(sql, columnNames);
        } finally {
            w.submitMicroTiming(sql);
        }
    }

    public int getResultSetHoldability() throws SQLException {
        return stmt.getResultSetHoldability();
    }

    public boolean isClosed() throws SQLException {
        return stmt.isClosed();
    }

    public void setPoolable(boolean poolable) throws SQLException {
        stmt.setPoolable(poolable);
    }

    public boolean isPoolable() throws SQLException {
        return stmt.isPoolable();
    }
}
